spring:
  data:
    mongodb:
      uri: mongodb://localhost/hello_world

loadprofile:
  pathone: "src/main/resources/Da+Db_[1, 1].csv"
  pathtwo: "src/main/resources/Dd+De_[1, 2].csv"

awattar:
  url: https://api.awattar.at/v1/marketdata

