spring:
  servlet:
    multipart:
      max-file-size: 1500KB
      max-request-size: 1500KB
  data:
    mongodb:
      uri: mongodb://localhost/energy_data
#      uri: mongodb+srv://evilgeniuses:evil1@energydata.7k9fm.mongodb.net/?retryWrites=true&w=majority
#      database: energydata

loadprofile:
  pathone: "src/main/resources/Da+Db_[1, 1].csv"
  pathtwo: "src/main/resources/Dd+De_[1, 2].csv"
  sourceone: "CSV1"
  sourcetwo: "CSV2"

awattar:
  url_future: https://api.awattar.at/v1/marketdata
  url_2019: https://api.awattar.at/v1/marketdata?start=1546297200000&end=1577833200000


