spring:
  data:
    mongodb:
      uri: mongodb+srv://evilgeniuses:evil@energydata.7k9fm.mongodb.net/?retryWrites=true&w=majority
      database: energydata


#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost/energy_data

loadprofile:
  pathone: "src/main/resources/Da+Db_[1, 1].csv"
  pathtwo: "src/main/resources/Dd+De_[1, 2].csv"
  sourceone: "CSV1"
  sourcetwo: "CSV2"

awattar:
  url_future: https://api.awattar.at/v1/marketdata
  url_2019: https://api.awattar.at/v1/marketdata?start=1546297200000&end=1577833200000


